### ISSUE TITLE
Minimal supported node version

### ISSUE THREAD

**Issue by martinsik** [laxa1986/gulp-angular-embed-templates#13]
Hey, maybe I've encountered an issue when using node `v0.12.7`. According to `package.json` the minimal supported version is `0.12.2`:

```
TypeError: undefined is not a function                                                                                                                                  
      at ChildClass.utils.extend.init (/var/www/my-ng2-project/shared/node_modules/gulp-angular-embed-templates/lib/ProcessorEngine.js:6:30)                
      at module.exports (/var/www/my-ng2-project/shared/node_modules/gulp-angular-embed-templates/index.js:54:21)                                           
      at Gulp.<anonymous> (/var/www/my-ng2-project/releases/20160307134801/gulpfile.js:63:15)                                                               
      at module.exports (/var/www/my-ng2-project/shared/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)                                    
      at Gulp.Orchestrator._runTask (/var/www/my-ng2-project/shared/node_modules/gulp/node_modules/orchestrator/index.js:273:3)                             
      at Gulp.Orchestrator._runStep (/var/www/my-ng2-project/shared/node_modules/gulp/node_modules/orchestrator/index.js:214:10)                            
      at Gulp.Orchestrator.start (/var/www/my-ng2-project/shared/node_modules/gulp/node_modules/orchestrator/index.js:134:8)                                
      at runNextSet (/var/www/my-ng2-project/shared/node_modules/run-sequence/index.js:88:16)                                                               
      at Gulp.onTaskEnd (/var/www/my-ng2-project/shared/node_modules/run-sequence/index.js:77:5)                                                            
      at Gulp.emit (events.js:129:20)                                                                                                                                                
      at Gulp.Orchestrator._emitTaskDone (/var/www/my-ng2-project/shared/node_modules/gulp/node_modules/orchestrator/index.js:264:8)                        
      at /var/www/my-ng2-project/shared/node_modules/gulp/node_modules/orchestrator/index.js:275:23                                                         
      at finish (/var/www/my-ng2-project/shared/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)                                            
      at /var/www/my-ng2-project/shared/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4                                                     
      at f (/var/www/my-ng2-project/shared/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)          
      at DestroyableTransform.onend (/var/www/my-ng2-project/shared/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)  
  [13:48:27] Error in plugin 'run-sequence'                                                                                                                                          
  Message:                                                                                                                                                                           
      An error occured in task 'app.build'.
```

It throws an error on [line 6 in `ProcessorEngine.js`](https://github.com/laxa1986/gulp-angular-embed-templates/blob/master/lib/ProcessorEngine.js#L6) when calling `Object.assign()` which is ES2015 feature not supported by node `0.12` branch.

See https://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign (it's listed under `Object static methods`). `Object.assign()` is supported since node `4.0`.

**Comment by laxa1986** [comment]
Fixed in 2.2.1
